name: Playwright Smoke Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      BASE_URL: ${{ vars.BASE_URL || 'https://www.funda.nl' }}
      FUNDA_UA: ${{ secrets.FUNDA_UA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run smoke tests (Chromium)
        run: npx playwright test --project=chromium
        continue-on-error: false

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7
          